# Create an event
POST http://localhost:8080/events HTTP/1.1
content-type: application/json
Authorization: TOKEN_HERE

{
    "name": "Test event",
    "description": "description for test event",
    "location": "location",
    "dateTime": "2025-01-02T15:30:00.000Z"
}

### 
# Get all events
GET http://localhost:8080/events HTTP/1.1

###
# Get event by id
GET http://localhost:8080/events/2 HTTP/1.1

###
# Update event by id
PUT http://localhost:8080/events/1 HTTP/1.1
content-type: application/json

{
    "name": "Updated event",
    "description": "description for updated event",
    "location": "location",
    "dateTime": "2025-01-02T15:30:00.000Z"
}

###
# Delete event by id
DELETE http://localhost:8080/events/1 HTTP/1.1
