# Create a user
POST http://localhost:8080/signup HTTP/1.1
content-type: application/json

{
    "email": "test3@gmail.com",
    "password": "test123"
}

### 

# Login a user
POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
    "email": "test2@gmail.com",
    "password": "test123"
}

### 